### ISSUE TITLE
PM::TableScreen cell editing_style: :delete not work

### ISSUE THREAD

**Issue by zhulinpinyu** [infinitered/redpotion#106]
TableScreen: swipe to delete not work. in RedPotion, ProMotion version is 2.3.1 also not work.
ProMotion 2.4.1 work well but 2.4.0 also not work.

Thanks.

**Comment by markrickert** [comment]
Can you please report this on the ProMotion gem repository? Thanks. 

https://github.com/clearsightstudio/ProMotion

**Comment by zhulinpinyu** [comment]
Hi markrickert,

RedPotion use ProMotion version is 2.3.1,so get this error.
https://github.com/infinitered/redpotion/pull/109

**Comment by squidpunch** [comment]
ih @zhulinpinyu I actually solved this in #108 - we just need to send a gem release.
