### ISSUE TITLE
Loosen RMQ and ProMotion dependencies

### ISSUE THREAD

**Issue by squidpunch** [infinitered/redpotion#107]
Interested in others thoughts on if there is a reason we should not do this?

I think that we should change our dependencies on RMQ and ProMotion to be less restrictive and only bump the requirement when we know there is new functionality in the dependent gem that we require.

Currently we have:
```ruby
spec.add_runtime_dependency "ruby_motion_query", "~> 1.4.0"
spec.add_runtime_dependency "ProMotion", "~> 2.3.1"
```

but is there any reason we should not do:
```ruby
spec.add_runtime_dependency "ruby_motion_query", ">= 1.4.0"
spec.add_runtime_dependency "ProMotion", ">= 2.3.1"
```

I have thought about this a few times, but if I read #106 correctly, I think the problem is there was a bug fixed in 1.4.1 of ProMotion - but as a user of RedPotion you are restricted to our next release - if we loosened the restriction like above - I as a user could bump ProMotion without any new redpotion release, and fix the underlying bug that was fixed in that product.

**Comment by markrickert** [comment]
![giphy](https://cloud.githubusercontent.com/assets/139261/7726813/8b2725d4-fed2-11e4-83c2-9f1b7e55f618.gif)

**Comment by jamonholmgren** [comment]
:+1:
