### ISSUE TITLE
undefined method `production?' for #<UIApplication:0x10d15b7f0>

### ISSUE THREAD

**Issue by andrewhavens** [infinitered/redpotion#118]
According to [the docs](http://docs.redpotion.org/en/latest/cookbook/project/), there is an `app.production?` method which is an alias of `release?`. I added some code to my App Delegate which runs some code that is intended for production/app store release, however I am seeing this error:

```
2015-06-02 15:49:22.878 app[98811:33490681] app_delegate.rb:7:in `on_load:': undefined method `production?' for #<UIApplication:0x10d15b7f0> (NoMethodError)
	from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
2015-06-02 15:49:22.890 app[98811:33490681] *** Terminating app due to uncaught exception 'NoMethodError', reason: 'app_delegate.rb:7:in `on_load:': undefined method `production?' for #<UIApplication:0x10d15b7f0> (NoMethodError)
	from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
'
```

Here is my code:

```
class AppDelegate < PM::Delegate
  status_bar true, animation: :fade

  def on_load(app, options)
    if app.production?
      $API_ROOT = 'https://production.example.com/api'
    elsif app.staging? # TODO: make this work since there is no iOS staging environment
      $API_ROOT = 'https://staging.example.com/api'
    elsif app.development?
      $API_ROOT = 'http://localhost:3000/api
    end
# ...
```

Am I doing something wrong?

**Comment by twerth** [comment]
app probably isn't in the PM:Deleate object. It's a shortcut to `rmq.app` or `find.app`. So you can use them. We should add it in RedPotion to PM::Delegate.

**Comment by andrewhavens** [comment]
Ah, yes, that solved the problem. I don't feel like this type of code belongs here anyway. Where do you typically define your environment config variables?

**Comment by squidpunch** [comment]
I cant speak for everyone else, but the way I handle it is something like this....
- a yaml file for each env (`production`, `staging`, `development`, `integration`, `travis`, etc...)
- when compiling an ENV value to tell which ENV `ENV=staging rake`
- my rakefile reads the config.yml, and writes a new class for me `app/settings.rb` that has all my settings 
- I can refer to them like `Settings.api_host` inside the app

this works pretty well for me, its all custom in my app though at the moment and uses the `rake-hooks` gem, I previously used [motion-config-vars](https://github.com/jamescallmebrent/motion-config-vars) but it would mess with the ENV, so `app.production` and `app.development` didnt work in the rake file, and it exposed all the ENV values in `Info.plist`
