### ISSUE TITLE
Having trouble changing color of title in nav bar in tab bar screen

### ISSUE THREAD

**Issue by andrewhavens** [infinitered/redpotion#123]
I have been able to change the color of the title within a regular screen. However, now I am using a tab bar and it is not applying the color to the title.

```ruby
class ListScreenStylesheet < ApplicationStylesheet
  def nav_bar
    controller.navigationController.navigationBar
  end

  def setup
    nav_bar.translucent = false
    nav_bar.barTintColor = color.dark_gray
    nav_bar.tintColor = color.white
  end
end
```

It is correctly changing the background color, but not changing the text of the title to white. However, it is changing the color of the right/left nav bar items to white text. From what I understand, `tintColor` controls the color of the title too. Am I doing something wrong?

**Comment by squidpunch** [comment]
I could be totally wrong but from what I recall I believe tint color is in fact just the bar buttons - title is set with `titleTextAttributes`

checked the docs quick, and looks like thats the case
![image](https://cloud.githubusercontent.com/assets/682263/8289787/918fd8b0-18ec-11e5-8400-74f9ef150310.png)
https://developer.apple.com/library/prerelease/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/UINavigationBar.html#//apple_ref/doc/uid/TP40012857-UINavigationBar-SW1

**Comment by andrewhavens** [comment]
Yeah, I've tried that too, but can't get it to work either.

```ruby
  def will_appear
    UINavigationBar.appearance.titleTextAttributes = {
      'UITextAttributeTextColor' => color.white
    }
    # also tried:
    navigationController.navigationBar.setTitleTextAttributes({
      UITextAttributeTextColor => color.white
    })
  end
```

**Comment by squidpunch** [comment]
is this a repo that I can clone and check it out?  I know that I have used something similar in a RMQ only app

**Comment by andrewhavens** [comment]
Just created a demo repository that contains this code: https://github.com/andrewhavens/redpotion-dark-navbar-example

Here's what I did:
* potion create navbarcolor
* add this code to `setup` method of `home_screen_stylesheet.rb`

```ruby
  def setup
    nav_bar = controller.navigationController.navigationBar
    nav_bar.translucent = false
    nav_bar.barTintColor = color.battleship_gray
    nav_bar.tintColor = color.white
    nav_bar.titleTextAttributes = {
      'UITextAttributeTextColor' => color.white
    }
  end
```

**Comment by twerth** [comment]
Didn't we add our appearance class to the template @squidpunch? If not, we should totally do that (assuming you even know what I'm talking about). Let me scrounge it up if it's not in there

**Comment by twerth** [comment]
It is not, I'll add it to the template now.

**Comment by squidpunch** [comment]
@twerth yeah you'll have to dig it up - not 100% sure what you have there.

@andrewhavens sounds like Todd might have a solution, but just in case tomorrow I will try and give this repo a look and see if I can figure out what's going on here.

**Comment by twerth** [comment]
This is how we always do this: https://github.com/infinitered/redpotion-template/commit/d33b129f69f9eb4b3758bf144a71869f714815d7

I added it to the RedPotion template. Although it could use some cleanup.

**Comment by andrewhavens** [comment]
Awesome, thanks! I've been searching all over for an example of applying app-wide styles!

**Comment by twerth** [comment]
If you find something wrong, would you please fix the template with a PR?

Appearance works fine, for what it does, but it's very inconsistent. It's worth using for whatever you can use it for.

**Comment by squidpunch** [comment]
awesome, I should try wiring this up in my app too - I knew you could do application wide but similar to @andrewhavens I didnt have any real examples that I could find.  

@andrewhavens let me know if that fixes your issue, or if you want me to dig into this sample app :+1:

**Comment by andrewhavens** [comment]
@squidpunch Yeah those `appearance` definitions worked for me.

```ruby
      UINavigationBar.appearance.tap do |o|
        o.translucent = false
        o.barTintColor = rmq.color.nav_bar_gray
        o.tintColor = rmq.color.white

        o.setTitleTextAttributes( {
          UITextAttributeTextColor => rmq.color.white
        })
      end
```

**Comment by squidpunch** [comment]
@andrewhavens awesome - I'll close this for now then!

thanks!

**Comment by dkrusenstrahle** [comment]
When I set translucent to false the grid stops working. I mean the grid is there but my UIView is not on the correct row anymore.
