### ISSUE TITLE
Searchable doesn't work anymore with redpotion 1.4.0 and ProMotion 2.4.2 

### ISSUE THREAD

**Issue by brunto** [infinitered/redpotion#138]

**Comment by jamonholmgren** [comment]
@twerth I thought we fixed this? cc @markrickert

**Comment by twerth** [comment]
@jamonholmgren perhaps we didn't roll it out yet?

**Comment by markrickert** [comment]
Correct. it's hasn't been rolled out. Use master for now.

**Comment by markrickert** [comment]
https://github.com/infinitered/redpotion/pull/135

**Comment by brunto** [comment]
Thank's

**Comment by markrickert** [comment]
No problem. We'll probalby do a new release soon that also fixes an issue with CDQ's dependencies.
