### ISSUE TITLE
UINavigationBar appearance not being applied

### ISSUE THREAD

**Issue by jonlunsford** [infinitered/redpotion#144]
Hi there, first of all, really great work!

### Issue

I'm having issues updating the `UINavigationBar` appearance from `StandardAppearance`. Uncommenting this block:

```ruby
UINavigationBar.appearance.tap do |o|
  o.barTintColor = rmq.color.black
  o.setTintColor rmq.color.black

  o.setTitleTextAttributes( {
    UITextAttributeFont => rmq.font.medium,
    UITextAttributeTextColor => rmq.color.white
    #UITextAttributeTextShadowColor => color.clear
  })
end
```
Yields no change to the styles.

### Env

 - iOS Simulator - iPhone 6 / iOS 8.4
 - redpotion (1.4.0)
 - Rubymotion 4.0 AND 3.14

Please let me know if you need any other info and any advice would be greatly appreciated!

**Comment by dsalzr** [comment]
+1. Any changes made for UINavigationBar in StandardAppearance don't take effect.

**Comment by mikowitz** [comment]
+1. I'm actually finding that no changes made in StandardAppearance seem to take effect.

* iOS Simulator iPhone 5s and 6 / iOS 9
* redpotion 1.4.0
* Rubymotion 4.3

**Comment by twerth** [comment]
This could be related to the ApplicationStylesheet is only initiated when it's first used. This is a problem that needs to be fixed. Try this in your app delegate on_load (first thing):

`ApplicationStylesheet.new(nil).application_setup`

**Comment by twerth** [comment]
That may not run before your screen is created though. You could put it directly in the app delegate class so it's run when the singleton code is run.

**Comment by dsalzr** [comment]
This worked for me.

Move StandardAppearance out of the ApplicationStylesheet and into the app delegate

def on_load(app, options)
    cdq.setup
    StandardAppearance.apply
    open TrainScreen.new(nav_bar: true)
end

**Comment by jonlunsford** [comment]
Thanks for the discussion! @twerth's suggestion worked for me. Are there any implications with manually instantiating `ApplicationStylesheet`? Will it be instantiated here AND as it normally does?

**Comment by mikowitz** [comment]
Thank's all! @twerth's suggestion to call

```ruby
ApplicationStylesheet.new(nil).application_setup
```

in the app delegate class works for me.

@dsalzr's suggestion works as well, but only if I'm not using any custom rmq colors/fonts/etc., since it seems those will not be loaded yet in `on_load`

**Comment by twerth** [comment]
There is no problem with that @jonlunsford , it will only happen once. We should just put that in RedPotion's app delegate class.

**Comment by twerth** [comment]
An easy PR for someone ^ :-)

**Comment by dsalzr** [comment]
Good point @mikowitz. I'll give @twerth's solution a try also.

**Comment by mikowitz** [comment]
I can PR it up unless someone else is on it already.

**Comment by mikowitz** [comment]
PR: https://github.com/infinitered/redpotion-template/pull/14
