### ISSUE TITLE
ProMotion-2.5.0 In Gemfile.lock says not found when run

### ISSUE THREAD

**Issue by dhf0820** [infinitered/redpotion#154]
I just updated to the latest RedPotion by doing a bundle update.  There were no errors however, when I attempt to do asloop:vrwizard-ios dhf$ bundle exec rake pod:install
Could not find ProMotion-2.5.0 in any of the sources
Run `bundle install` to install missing gems.
Updating spec repo `master`
Updating 67f358c..01338c5
Fast-forward
 Specs/LaunchKit/1.0.5/LaunchKit.podspec.json | 21 +++++++++++++++++++++
 Specs/VinceRP/0.2.2/VinceRP.podspec.json     | 36 ++++++++++++++++++++++++++++++++++++
 2 files changed, 57 insertions(+)
 create mode 100644 Specs/LaunchKit/1.0.5/LaunchKit.podspec.json
 create mode 100644 Specs/VinceRP/0.2.2/VinceRP.podspec.json
From https://github.com/CocoaPods/Specs
   67f358c..01338c5  master     -> origin/master
Name: vrwizard-ios

I did a direct gem install and still get the same thing. 

Starting the app gives:
rake
Could not find ProMotion-2.5.0 in any of the sources
Run `bundle install` to install missing gems.

Gemfile.lock has:
GEM
  remote: https://rubygems.org/
  specs:
    ProMotion (2.5.0)
      methadone (~> 1.7)
      motion_print (~> 1.0)
    RedAlert (1.4)
      ruby_motion_query (>= 1.3.4)
....

**Comment by jamonholmgren** [comment]
Sorry about that, @dhf0820 , we haven't released a new version of RedPotion that is compatible with ProMotion 2.5.x yet. We'll do that soon; in the meantime, feel free to version lock ProMotion at 2.4.x.

**Comment by dhf0820** [comment]
I understand that, however I have both versions on my machine and created a new
app with potion ant it fails to run.
Don French

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On Tue, Nov 24, 2015 at 4:30 PM, Jamon Holmgren <notifications@github.com>
wrote:
Sorry about that, @dhf0820 [https://github.com/dhf0820] , we haven't released a new version of RedPotion that is compatible with
ProMotion 2.5.x yet. We'll do that soon; in the meantime, feel free to version
lock ProMotion at 2.4.x.

—
Reply to this email directly or view it on GitHub
[https://github.com/infinitered/redpotion/issues/154#issuecomment-159447558] .[https://github.com/notifications/beacon/AABcq2XLpasRNomvK0bQmZKOTpge--Xdks5pJPiSgaJpZM4GnzGt.gif]

**Comment by squidpunch** [comment]
I released a new version of redpotion (1.5) yesterday. If you bundle update redpotion does this solve your problem?

**Comment by dhf0820** [comment]
Seems to fix it however even after bundling I get the error "Could not find ProMotion-2.5.0 in any of the sources".  I looked in the Gemfile.lock and it is there.

**Comment by dhf0820** [comment]
Additional question. Is there a good example that uses the RedPotion using  PM/RMQ/CDQ to create a simple app that accepts some data, saves it and shows it in a table?

**Comment by dhf0820** [comment]
I spoke too soon it fails when start up with undefined method 'set_searchable_param_defaults' for module 'ProMotion::Table::Searchable'

**Comment by squidpunch** [comment]
sounds like your gem versions aren't updated.
`bundle show ProMotion`
`bundle show redpotion`

`bundle update redpotion` (which should update ProMotion if its not already updated)

I don't know of any samples off the top of my head iwth PM/RMQ/CDQ - the sample app in redpotion does have some some examples of using them together.

**Comment by squidpunch** [comment]
@dhf0820 I'm going to close this issue, as I think it should be resolved.  Let me know if thats not the case and we can re-open and investigate further, thanks.
