### ISSUE TITLE
Sorry, image= is not implemented on RubyMotionQuery::Stylers::UIViewStyler

### ISSUE THREAD

**Issue by dhf0820** [infinitered/redpotion#157]
I am trying to add an image to a layout using st.image = image.resource('icon_msg') in the stylesheet. I tried it even with a default image that is part of the template.

I get: Sorry, image= is not implemented on RubyMotionQuery::Stylers::UIViewStyler. This will produce a crash when not in debug mode.

This is on RP = 1.5.0, ruby_motion_query (>= 1.7.0) from Gemfile.lock

**Comment by squidpunch** [comment]
Yeah it's a valid warning.

You'll want to use an UIImageView or use background_image that styler isn't on UIView

**Comment by dhf0820** [comment]
Thank you.  That will cure me from using examples to learn from. The example was wrong.

**Comment by squidpunch** [comment]
No worries!  Is this an example in the redpotion docs?  I can update of so!

**Comment by dhf0820** [comment]
I will attempt to find it again. It was an example of an RMQ.  What is really needed is how to handle keyboard showing and hiding plus the textFieldShouldReturn the RMQ/PM way.
