### ISSUE TITLE
possibility multiple allocation for custom TableViewCell?

### ISSUE THREAD

**Issue by apinrdw** [infinitered/redpotion#158]
Hi, first thanks for all working on this gem that helps me a lot.

i  when to see this slides https://www.icloud.com/keynote/000CT87bOpMcS7-T3I7jvrwNg#Inspect_2015_-_RedPotion_In_Practice and try new concept for layout instead of using instance variable for each `UIControl` in subclass of `PM::TableViewCell`. where i can said this is the best approach to make code clean.

but i catch a possibility multiple allocation using it when reuse the cell. i create sample repo for testing this issue [here](https://github.com/apinrdw/cell-buggy).

any good way to handle this? thanks...
sorry bad english :grin:

**Comment by andrewhavens** [comment]
@apinrdw The problem is you are calling `append` in your `post=` method. This method is called when the cell is reused. You should only call append in `on_load`.

**Comment by apinrdw** [comment]
@andrewhavens thanks for the reply.

yes, you are right. try `append!` in `on_load` method, but the `self.table_screen` is not initialize in `on_load` method. how can i access the stylesheet from there?

**Comment by squidpunch** [comment]
@apinrdw if you add the appending of the views in the `on_load` of the cell, and then update the date in the `post=` method, you should create the proper views and not duplicate them.  The cell should be the one that is responsible for adding views to it, rather than the stylesheet (in my opinion).

I sent a PR to your sample with the fixes I would do to solve your issue.

**Comment by andrewhavens** [comment]
I think the answer to your question is that your can call `rmq.screen.stylesheet` to access the current screen's stylesheet.

**Comment by squidpunch** [comment]
that works too (and you can drop the `rmq` and just call `screen`).  Though I personally still prefer the view be the place to find what views have been attached to it - but either should work

**Comment by apinrdw** [comment]
great there is 2 options to solve this.

thanks for the support :smile:
