### ISSUE TITLE
First "big" feature: ProMotion tables + core data

### ISSUE THREAD

**Issue by skandragon** [infinitered/redpotion#16]
... and I have no idea how to implement it, but it would be wonderfully nice if one could have an easy way to tie in core data into a ProMotion TableScreen.

**Comment by twerth** [comment]
This is done right?

**Comment by squidpunch** [comment]
From my point of view, I thought so.  Was waiting to hear from @skandragon or others if they actually were using it and see how it was going - there is an example of it in the sample app though.

**Comment by skandragon** [comment]
Sorry, I've managed to get swamped and not have a chance recently to come back to the app I was working on.
