### ISSUE TITLE
iOS 11 Support

### ISSUE THREAD

**Issue by jwg2s** [infinitered/redpotion#180]
Hi, we're trying to build against the iOS 11 beta but realized the `deployment_target` of iOS 11 isn't supported.  Is this something you're working on?  Anything we can help with?

**Comment by andrewhavens** [comment]
@jwg2s Have you identified something specifically that isn't supported? I'm not sure that the latest version of RubyMotion supports iOS 11 yet (though I hear that a new version of RM will be out soon).

**Comment by jwg2s** [comment]
@andrewhavens you're right, I misinterpreted the errors I was reading.  Just did some digging and realized the same thing.
