### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by andrewhavens** [infinitered/redpotion#183]
@jamonholmgren @twerth Please add a LICENSE file to this repo.

**Comment by twerth** [comment]
Will do Andrew, IIRC, it's MIT license. I'll verify and add it. Feel free to add it yourself too if you like.

**Comment by andrewhavens** [comment]
@twerth Look good to you? https://github.com/infinitered/redpotion/blob/master/LICENSE

**Comment by twerth** [comment]
@andrewhavens Looks awesome to me. Thanks sir
