### ISSUE TITLE
Socket error when running 'rake' in new redpotion app.

### ISSUE THREAD

**Issue by timspiller** [infinitered/redpotion#184]
Tims-MacBook-Pro-2:~ tspiller$ **cd my_new_app**
Tims-MacBook-Pro-2:my_new_app tspiller$ **rake**
Name: my_new_app
Using profile: /Users/tspiller/my_new_app/signing/my_new_app.mobileprovision
Using certificate: iPhone Developer: YOURNAME
Generating Data Model my_new_app
   Loading schemas/0001_initial.rb
   Writing resources/my_new_app.xcdatamodeld/0001 initial.xcdatamodel/contents
     Build ./build/iPhoneSimulator-12.1-Development
     Build /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cdq-1.0.6/lib/../vendor/cdq/ext
     Build /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/motion-yaml-1.4/lib/YAMLKit
  WARNING! Possible cyclical dependency between /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ProMotion-2.8.2/lib/ProMotion/collection/data/collection_data.rb and /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ProMotion-2.8.2/lib/ProMotion/collection/collection.rb's class hierarchy. Consider revision if runtime exceptions occur around undefined symbols.
  WARNING! Possible cyclical dependency between /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ProMotion-2.8.2/lib/ProMotion/table/data/table_data.rb and /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ProMotion-2.8.2/lib/ProMotion/table/table.rb's class hierarchy. Consider revision if runtime exceptions occur around undefined symbols.
  WARNING! Possible cyclical dependency between /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/RedAlert-1.5/lib/project/alert_action.rb and /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/RedAlert-1.5/lib/project/red_alert.rb's class hierarchy. Consider revision if runtime exceptions occur around undefined symbols.
  WARNING! Possible cyclical dependency between /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/RedAlert-1.5/lib/project/alert_action.rb and /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/RedAlert-1.5/lib/project/red_alert.rb's class hierarchy. Consider revision if runtime exceptions occur around undefined symbols.
  WARNING! Possible cyclical dependency between /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/RedAlert-1.5/lib/project/alert_action.rb and /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/RedAlert-1.5/lib/project/red_alert.rb's class hierarchy. Consider revision if runtime exceptions occur around undefined symbols.
  WARNING! Possible cyclical dependency between /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cdq-1.0.6/lib/../motion/managed_object.rb and /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cdq-1.0.6/lib/../motion/cdq/targeted_query.rb's class hierarchy. Consider revision if runtime exceptions occur around undefined symbols.
  WARNING! Possible cyclical dependency between /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ruby_motion_query-1.7.0/lib/../motion/ext.rb and /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ruby_motion_query-1.7.0/lib/../motion/ruby_motion_query/grid.rb's class hierarchy. Consider revision if runtime exceptions occur around undefined symbols.
  WARNING! Possible cyclical dependency between /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/redpotion-1.7.1/lib/project/pro_motion/data_table.rb and /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/redpotion-1.7.1/lib/project/pro_motion/table.rb's class hierarchy. Consider revision if runtime exceptions occur around undefined symbols.
  WARNING! Possible cyclical dependency between /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/redpotion-1.7.1/lib/project/pro_motion/data_table.rb and /Users/tspiller/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/redpotion-1.7.1/lib/project/pro_motion/table.rb's class hierarchy. Consider revision if runtime exceptions occur around undefined symbols.
**rake aborted!
SocketError: getaddrinfo: nodename nor servname provided, or not known
/Library/RubyMotion/lib/motion/project/xcode_config.rb:704:in `initialize'
/Library/RubyMotion/lib/motion/project/xcode_config.rb:704:in `new'
/Library/RubyMotion/lib/motion/project/xcode_config.rb:704:in `local_repl_port'
/Library/RubyMotion/lib/motion/project/builder.rb:232:in `build'
/Library/RubyMotion/lib/motion/project/app.rb:78:in `build'
/Users/tspiller/.rubymotion/rubymotion-templates/motion/project/template/ios.rb:70:in `block (2 levels) in <top (required)>'
/Users/tspiller/.rubymotion/rubymotion-templates/motion/project/template/ios.rb:183:in `block in <top (required)>'
Tasks: TOP => build:simulator
(See full trace by running task with --trace)**
Tims-MacBook-Pro-2:my_new_app tspiller$

**Comment by andrewhavens** [comment]
Hi @timspiller, reviewing the backtrace, it looks like RubyMotion was having trouble launching the REPL due to some sort of DNS/port error. It doesn't look like this issue is specific to RedPotion, so I'm going to close this issue. If you continue running into this issue, I would recommend joining our Slack workspace (https://motioneers.herokuapp.com) and asking for help and/or reporting the issue here: https://github.com/amirrajan/rubymotion-applied/issues

**Comment by timspiller** [comment]
Thanks Andrew!
