### ISSUE TITLE
Remove default Pods/Gems as needed

### ISSUE THREAD

**Issue by GantMan** [infinitered/redpotion#30]
A beginner to RubyMotion won't know anything about AFnetworking or CDQ.  We'd love the gem to still be fore them.   So lets add a few potion tasks to remove CDQ after the fact.

```
potion remove cdq
postion remove afmotion
```

**Comment by twerth** [comment]
Is this all done now?

**Comment by squidpunch** [comment]
@twerth both `remove` commands are added, I didnt add a `-- skip afmotion` command, should I add that too and call it complete?

**Comment by squidpunch** [comment]
final piece ready in #35
