### ISSUE TITLE
"potion create model foo" hangs

### ISSUE THREAD

**Issue by twerth** [infinitered/redpotion#43]
`potion create model foo` just sits there, waiting for something, the train perhaps.

**Comment by twerth** [comment]
Looks like `potion create shared some_class_used_app_wide` does also and `potion create lib some_class_used_by_multiple_apps` and `potion create controller foos`

Creating screens and a view work.

**Comment by squidpunch** [comment]
hrmm, I was pretty sure I tested every creation the last time I tweaked the generator - I will look at this when i look at the remove flag.
