### ISSUE TITLE
potion create model foo hangs

### ISSUE THREAD

**Issue by Siggs2000** [infinitered/redpotion#45]
This is majorly harmless bug but I thought I'd report it anyway just so it's known. 

For some reason the `potion create model model_name` hangs when I try it. If I go for `rmq create model model_name` instead, it works without issue. 

I'm have redpotion v 0.7.1, rmq 1.1.0, promotion 2.2.1(only `redpotion` is in the gemfile though)

It seems to hang forever before anything is outputted to the terminal until I control+c

**Comment by squidpunch** [comment]
@twerth did you release again after #44 merge?

**Comment by twerth** [comment]
I have not yet, I need that CDQ bug fixed first.

**Comment by GantMan** [comment]
@Siggs2000  This bug is fixed (by @squidpunch ) and will release in the next version of Redpotion :)

**Comment by Siggs2000** [comment]
Sweet! Love this gem btw!
