### ISSUE TITLE
Use CDQ generators if included

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/redpotion#48]
Currently uses RMQ generic model generators, but should use CDQ's generators instead if it's included.

**Comment by squidpunch** [comment]
I wonder if there is a case that we want two generators - a data based one (CDQ) versus a non backed one which (regular RMQ)  this is part of the reason I haven't worked something like this up yet.

thoughts everyone?

**Comment by twerth** [comment]
2 would be nice, but I think CDQ one should be default.
