### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by twerth** [infinitered/redpotion#62]
Be nice to have repo based documentation, but not in the ReadMe. In markdown. Something people can do a PR for. Perhaps a script to push it to wherever it lives. Like ProMotion does.

**Comment by squidpunch** [comment]
@jamonholmgren what do you guys use for this?  Would be cool to get this implemented.

**Comment by jamonholmgren** [comment]
We use readthedocs.org.

http://promotion.readthedocs.org/en/master/

You can point to different branches and tags:

http://promotion.readthedocs.org/en/version-2.3/

We did have to specify the table of contents manually, but it's not very hard:

https://github.com/clearsightstudio/ProMotion/blob/version-2.3/mkdocs.yml

Then you get your glorious `./docs` folder: https://github.com/clearsightstudio/ProMotion/tree/version-2.3/docs

And you can require all pull requests to have documentation updates as well, like we are going to do.

ReadTheDocs has a Github hook and rebuilds on every commit.

**Comment by twerth** [comment]
You know the sad thing, I didn't even know about these docs for ProMotion until Jamon mentioned it to me.

**Comment by twerth** [comment]
Regardless if we used something like readthedocs, I really like the /docs folder idea with .md files in it.

**Comment by jamonholmgren** [comment]
@twerth It's a pretty new thing, actually. I exported the wiki and built the docs folder. I agree the /docs folder is almost good enough as-is -- add a README.md for an index in that folder, too.

**Comment by jamonholmgren** [comment]
When searching the code base using Github search, you get documentation results too. That's a big win.

**Comment by twerth** [comment]
How does that work Jamon, I can't search ProMotion docs using github's search?

**Comment by twerth** [comment]
I think RMQ and ProMotion's docs should be complete reference, but for RedPotion, I think it should be cookbook style. Thoughts?

**Comment by jamonholmgren** [comment]
You won't be able to until we merge them into master. But then they'll be in the code base, so searchable.

:+1: cookbook for red potion.

**Comment by GantMan** [comment]
I've already started your cookbook.

**Comment by twerth** [comment]
You mean actual searching of the .md files? Not the wiki or whatever. This is what has turned me off from using Github for docs.

**Comment by twerth** [comment]
So for cookbook, I was thinking less a series of projects, but just docs with examples of how to do everything. We can use a lot of the docs from ProMotion and RMQ, and Gant's cookbook, etc.

**Comment by jamonholmgren** [comment]
> You mean actual searching of the .md files? Not the wiki or whatever. This is what has turned me off from using Github for docs.

Yeah, actual searching of .md files. Only works when it's in the primary branch of the primary repo.

**Comment by twerth** [comment]
Closing as this is now in the repo

**Comment by manju-ms** [comment]
How to create a table with multiple columns ?

**Comment by markrickert** [comment]
@manju-ms What you're looking for here is called a `UICollectionView`. Tables can only have one column. Once you've created your redpotion project you can easily generate a collectionview with the command `potion g collection_view_screen` Hope that helps.
