### ISSUE TITLE
Idea: DataTableScreen refreshes row automatically when the model file is saved to core data

### ISSUE THREAD

**Issue by markrickert** [infinitered/redpotion#66]
So I think this might be a really killer feature to have:

I have my managed object:

```ruby
class Whatever < CDQManagedObject
end
```

and a `PM::DataTableScreen` that displays its contents.

Core data ManagedObjects give us a `didSave` method that's called when core data saves the file to the store. I've verified that it's called when you do a `cdq.save`.

Now we need to figure a way to remember what position its in in the table and then just call 
```ruby
update_table_data(NSIndexPath.indexPathForRow(x, inSection:y))
```

Thoughts on how we might achieve this?

**Comment by jamonholmgren** [comment]
Perhaps WeakRef a delegate (the TableScreen) in the model and call back to an `on_cdq_save` method, which in turn calls that `update_table_data` method? But then, we'll need to know what index path to reference.

**Comment by markrickert** [comment]
Yeah. The big problem to solve is how we know what model instance goes with what row.

**Comment by jamonholmgren** [comment]
The TableScreen could actually set the delegate and the index path at the same time as virtual attributes on the model. Looking into the source now...

**Comment by jamonholmgren** [comment]
Somewhere around [here](https://github.com/infinitered/redpotion/blob/data-table-cell-template/lib/project/pro_motion/data_table_screen.rb#L41) track the current index path and set it as one of the properties of the cell. Maybe even in the `rmq_data` for the cell.

**Comment by jamonholmgren** [comment]
Oops, wrong direction. We need the index path set on the data model.

**Comment by jamonholmgren** [comment]
We do have the `c` reference, which is the data model. Set the `data_table_delegate` and `data_table_index_path` there.

**Comment by markrickert** [comment]
Can you elaborate on this a bit more?

**Comment by jamonholmgren** [comment]
Yeah, lemme give the code a shot here.

**Comment by jamonholmgren** [comment]
```ruby
module TableModel
  def rp_data
    @rp_data ||= {}
  end

  def didSave
    rp_data[:table_data_delegate].send("on_cdq_save:", self) if rp_data[:table_data_delegate].respond_to?("on_cdq_save:")
  end
end
```

```ruby
    def cell_data
      return [] if cell_properties.nil?
      return [] if data_model.nil?

      data_model.send(data_scope).collect do |c|
        c.extend TableModel unless c.is_a?(TableModel)
        c.rp_data[:data_table_delegate] = WeakRef.new(self)
        c.rp_data[:index_path] = <some index path ref here, manually tracked?>
        if c.respond_to?(:cell)
          c.cell
        else
          {
            cell_class: cell_class,
            properties: properties.inject({}) do |hash, element|
              hash[element.first] = c.send(element.last)
              hash
            end
          }
        end
      end
    end

    def on_cdq_save(obj)
      update_table_data(index_path: obj.rp_data[:index_path])
    end
```

**Comment by markrickert** [comment]
I've got this feature in the data table screen branch. Closing.

**Comment by squidpunch** [comment]
:+1:
