### ISSUE TITLE
Test for content in a custom table cell view

### ISSUE THREAD

**Issue by carlinisaacson** [infinitered/redpotion#74]
I am using a custom cell class in a table cell and passing it state. 

Here is my table cell view:
```ruby
class CustomCell < PM::TableViewCell
  def state=(state)
    build_initial_view unless view_built? # Lay out view unless already laid out
    find(contentView).tap do |c|
      c.find(:label).data(state[:key]) if state[:key] # Pass state to views
    end
  end

  def view_built?
    @view_built
  end

  def build_initial_view
    find(contentView).tap do |c|
      c.append(UILabel, :label)
    end
    @view_built = true
  end
end
```

In my spec I can then set my view's state by doing something like this:
```ruby
describe CustomCell do
  def cell
    @cell ||= CustomCell.new
  end

  def default_state
    {  key: "value"  }
  end

  before do
    cell.state = default_state # Setting state
  end

  after do
    @cell = nil
  end
end
```

What I am trying to do is then test for content like this:
```ruby
it "has content" do
  cell.find(:label).data.should == "value"
end
```

When I run my spec I get this error:
```bash
  CustomCell has content: FAILED - [].==("value") failed
```

Any other ways of trying to find the view have failed as well. I either get `nil` or an empty array as in the above error.

My question is, how can I check that my views have the correct data in my view spec?

**Comment by squidpunch** [comment]
I think @jamonholmgren mentioned this, I can poke around a bit at it when I get some free time.

you should be able to use `rmq_build` for the initial state stuff too - unless I am overlooking something. 

In any event I plan to throw together a quick app and test this out, see if I can reproduce it, and then try and figure out whats going on here - thanks for reporting it @carlinisaacson

**Comment by squidpunch** [comment]
@carlinisaacson I can recreate the problem with a sample app - going to see if I can come up with a working solution.  I have a feeling this has something to do with the rmq context guessing the wrong parent - I've had discussions with @twerth about this kind of thing in the past, and that was the end result

if you do something like `mp cell.find(:label).count` in your test - I expect that you will get `0`

If you are getting the same thing in your view in the `state` method (a zero count when selecting) then that could be why you are getting data back as nil as well.


I havent really dug into this far enough to give any insights yet - but this is some ideas to try and troubleshoot some.  I am going to try and look at this closer tonight if there is room on the train or possibly tomorrow.

**Comment by carlinisaacson** [comment]
Thanks @squidpunch. I tried what you suggested.

If I place the `mp` in my `state` method like this: 
```ruby
def state=(state)
  build_initial_view unless view_built? # Lay out view unless already laid out
  find(contentView).tap do |c|
    mp c.find(:label).count
    c.find(:label).data(state[:key]) if state[:key] # Pass state to views
  end
end
```
and run the simulator I get a count of 1 for each cell, but when I run my specs I get a count of 0.

**Comment by squidpunch** [comment]
yeah so its how we are interacting with the view outside in the specs.  Will let you know when i dig into it further and hopefully help get it sorted!

**Comment by squidpunch** [comment]
@carlinisaacson so I have quick fix, though I wonder if we could patch this to be smarter.  Its all about the RMQ context, and in the specs it attaches to the wrong things at times, and can cause confusion (I know it has for me in the past...)

In any event the quick solution is to put this in your spec instead...
`rmq(cell).find(:label).data.should == "value"`

I created a quick gist to show your starting point, the test fix, and the rmq build stuff I was talking about above: https://gist.github.com/squidpunch/0964cb329058d10c28d0

I'm going to look a little closer to see if we can get it work as expected in specs (cell.find should really already be in the right context...I thought)

**Comment by squidpunch** [comment]
think this exposes a bug - going to verify and PR a fix, but like I said the workaround should unblock you :+1:
