### ISSUE TITLE
Live reloading for PM Screens

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/redpotion#96]
I'm working on it. Should hook into `live`.

Also, would like to output an info debug when loading the simulator up:

```
[RedPotion] Type in `live` to enable live reloading of screens and stylesheets
> 
```

**Comment by squidpunch** [comment]
:+1:

**Comment by zxiest** [comment]
This would be pretty awesome! Very looking forward to it!

**Comment by twerth** [comment]
Good idea Jamon.

**Comment by andrewhavens** [comment]
Pretty sure live reload broke when `eval` was removed from RubyMotion. Closing this until it becomes relevant again.
